name: C++ Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: sudo apt-get install -y g++
    - name: Build with Makefile
      run: make
