name: CI Workflow

on:
  push:
    branches:
      - branchMake
      - branchAutomake
      - branchAutoPackage
  pull_request:
    branches:
      - branchMake
      - branchAutomake
      - branchAutoPackage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ automake autoconf devscripts debhelper build-essential

    - name: Build with Makefile
      if: github.ref == 'refs/heads/branchMake'
      run: make

    - name: Build tarball
      if: github.ref == 'refs/heads/branchAutomake'
      run: |
        autoreconf --install
        ./configure
        make dist

    - name: Build Debian package
      if: github.ref == 'refs/heads/branchAutoPackage'
      run: |
        autoreconf --install
        ./configure
        dpkg-buildpackage -us -uc
        ls -lh ../*.deb
